version: "3.8"
services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - "/home/ec2-user/EAPP/onlinepipe:/usr/share/nginx/html/"
      - "logvolume01:/var/log"
volumes:
  logvolume01: {}
